apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 4