kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud-kubernetes
  
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
   
roleRef:
  kind: ClusterRole
  name: spring-cloud-kubernetes
  apiGroup: ""
