apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: gateway-service-svc
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000