apiVersion: v1
kind: Service
metadata:
  
  name: gateway-service-svc
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      name: http
      port: 9091
      targetPort: 5000